development:
  adapter: postgresql
  encoding: unicode
  database: santrovelo
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: santrovelo_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: santrovelo
  pool: 5